openapi: 3.0.0
info:
  title: LAP-Juice API
  description: This is the API documentation for LAP-Juice API.
  version: 0.1.9

host: localhost:3000
basePath: /
schemes:
  - http

paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200":
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /juice:
    get:
      summary: Returns a list of juices.
      description: Get the juice list in JSON format.
      responses:
        "200":
          description: A JSON array of juice objects
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    brand_code:
                      type: integer
                    brand:
                      type: string
                    description:
                      type: string

    post:
      summary: Create a new juice.
      description: Create a juice by providing the required fields.
      requestBody:
        description: Juice object that needs to be added to the store.
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - brand_code
                - brand
                - description
              properties:
                brand_code:
                  type: integer
                brand:
                  type: string
                description:
                  type: string
      responses:
        "201":
          description: Juice created successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  result:
                    type: object
                    properties:
                      id:
                        type: string
                      brand_code:
                        type: integer
                      brand:
                        type: string
                      description:
                        type: string
        "400":
          description: Invalid input.
        "500":
          description: Internal server error.

  /juice/{id}:
    get:
      summary: Get juice details by ID.
      description: Returns the details of a specific juice item.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A detailed juice object.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  result:
                    type: object
                    properties:
                      brand_code:
                        type: integer
                      brand:
                        type: string
                      description:
                        type: string
        "404":
          description: Juice not found.

    put:
      summary: Update an existing juice by ID.
      description: Update the details of a juice item.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: Fields to update for the juice item.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                brand_code:
                  type: integer
                brand:
                  type: string
                description:
                  type: string
      responses:
        "200":
          description: Juice updated successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  result:
                    type: object
                    properties:
                      id:
                        type: string
                      brand_code:
                        type: integer
                      brand:
                        type: string
                      description:
                        type: string
        "404":
          description: Juice not found.

    delete:
      summary: Delete a juice by ID.
      description: Delete a specific juice item.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Juice deleted successfully.
        "404":
          description: Juice not found.
